source 'https://rubygems.org'

# gem 'kitchen-docker', '~> 2.6'
gem 'kitchen-dokken'

gem 'berkshelf'
gem 'chefspec', '~> 7.1.0'
gem 'foodcritic'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-kitchen', github: 'trickyearlobe/guard-kitchen', branch: 'support_guard_2'
gem 'guard-rspec'
gem 'guard-rubocop'
gem 'inspec'
gem 'kitchen-inspec'
gem 'pry-coolline'
gem 'rubocop'
