# Basicly taken from:
# https://github.com/docker-library/drupal/issues/3#issuecomment-153775540
#
# Volume containers are the way to go.

version: '2'
services:
  drupal:
    image: drupal:8.5
    restart: always
    links:
      - "db:mysql"
    ports:
      - "8082:80"
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites

  db:
    image: mysql
    restart: always
    volumes:
      - storage-mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
      - MYSQL_DATABASE=drupal8
      - MYSQL_ROOT_PASSWORD=db_root_pass
volumes:
  storage-mysql:
    driver: local
  drupal-modules:
    driver: local
  drupal-profiles:
    driver: local
  drupal-themes:
    driver: local
  drupal-sites:
    driver: local
